version: '3.2'
services:

    # https://github.com/diginc/docker-pi-hole
    # https://hub.docker.com/r/diginc/pi-hole/
    pihole:
        image: "diginc/pi-hole:arm"
        volumes:
            - ./config:/etc/pihole
            - ./dnsmasq.d:/etc/dnsmasq.d
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "80:80"
        env_file:
            - ./pihole.env
        networks:
            - overlay_net
        healthcheck:
            test: curl --fail http://localhost:80/admin/ || exit 1

# volumes:
#     config_vol:
#     dnsmasq.d_vol:

networks:
    overlay_net:
        driver: overlay
